/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 21 16:02:07 GMT 2022
 */

package org.apache.tika.sax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tika.sax.TaggedSAXException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.xml.sax.SAXException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TaggedSAXException_ESTest extends TaggedSAXException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SAXException sAXException0 = mock(SAXException.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(sAXException0).getMessage();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, (Object) null);
      Object object0 = taggedSAXException0.getTag();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SAXException sAXException0 = new SAXException();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, (Object) null);
      TaggedSAXException taggedSAXException1 = null;
      try {
        taggedSAXException1 = new TaggedSAXException((SAXException) null, taggedSAXException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tika.sax.TaggedSAXException", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SAXException sAXException0 = mock(SAXException.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(sAXException0).getMessage();
      doReturn((String) null).when(sAXException0).toString();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, sAXException0);
      Object object0 = taggedSAXException0.getTag();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SAXException sAXException0 = new SAXException();
      TaggedSAXException taggedSAXException0 = new TaggedSAXException(sAXException0, sAXException0);
      SAXException sAXException1 = taggedSAXException0.getCause();
      assertSame(sAXException0, sAXException1);
  }
}
