/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 21 15:58:25 GMT 2022
 */

package org.apache.tika.io;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.tika.io.IOExceptionWithCause;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IOExceptionWithCause_ESTest extends IOExceptionWithCause_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IOExceptionWithCause iOExceptionWithCause0 = new IOExceptionWithCause((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("7");
      IOExceptionWithCause iOExceptionWithCause0 = new IOExceptionWithCause(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IOExceptionWithCause iOExceptionWithCause0 = new IOExceptionWithCause("_,4", (Throwable) null);
  }
}
