/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 22 01:36:32 GMT 2022
 */

package org.apache.tika.sax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tika.sax.TaggedContentHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TaggedContentHandler_ESTest extends TaggedContentHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TaggedContentHandler taggedContentHandler0 = new TaggedContentHandler((ContentHandler) null);
      // Undeclared exception!
      try { 
        taggedContentHandler0.handleException((SAXException) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tika.sax.TaggedSAXException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ContentHandler contentHandler0 = mock(ContentHandler.class, new ViolatedAssumptionAnswer());
      TaggedContentHandler taggedContentHandler0 = new TaggedContentHandler(contentHandler0);
      Exception exception0 = mock(Exception.class, new ViolatedAssumptionAnswer());
      taggedContentHandler0.throwIfCauseOf(exception0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ContentHandler contentHandler0 = mock(ContentHandler.class, new ViolatedAssumptionAnswer());
      TaggedContentHandler taggedContentHandler0 = new TaggedContentHandler(contentHandler0);
      SAXException sAXException0 = mock(SAXException.class, new ViolatedAssumptionAnswer());
      boolean boolean0 = taggedContentHandler0.isCauseOf(sAXException0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ContentHandler contentHandler0 = mock(ContentHandler.class, new ViolatedAssumptionAnswer());
      TaggedContentHandler taggedContentHandler0 = new TaggedContentHandler(contentHandler0);
  }
}
